@url_dev = http://localhost:3052/v1/api

### signup
POST {{url_dev}}/kata/signup
Content-Type: application/json
x-api-key: 8dc7a4a9467f094c9354e408c32526b1b1c255d1ce34cc84a574ab14881fa025e77c52df4de20d5dfa5bb1a269ec0e8544cb6c793acd06f1b113409f53fce3ef


{
    "name": "Quick Think",
    "email": "quickthink@gmail.com",
    "password": "qwer1234"
}
