@url_dev = http://localhost:3052/api/v1

### signup
POST {{url_dev}}/kata/signup
Content-Type: application/json

{
    "name": "Nguyen Quoc Thinh",
    "email": "thinhb2106815@student.ctu.edu.vn",
    "password": "fghj6789"
}

###signin
POST {{url_dev}}/kata/signin
Content-Type: application/json

# {
#     "email": "quickthink@gmail.com",
#     "password": "fghj6789"
# }

{
    "email": "quickthink123@gmail.com",
    "password": "fghj6789"
}


### reset password
POST {{url_dev}}/kata/reset-password/kasdjfk
Content-Type: application/json

{
    "password": "abcd1234"
}